//! The eleven cross-cutting typed string identifiers.
//!
//! Each is a `#[repr(transparent)]` newtype over `Arc<str>` (the Rust IDs are
//! `UUIDv4` strings and prefixed strings such as `root-<hex16>`, so the inner
//! type is a string slice, never an integer — hence not `Copy`). `Arc<str>`
//! makes the pervasive id clones across the control plane O(1) atomic refcount
//! bumps rather than heap allocations, while keeping the value immutable after
//! mint. All are generated by the `pub(crate)` [`define_id!`] codegen helper
//! (DRY); it is an internal helper, not a public extension point, and is not
//! re-exported.

/// Generate a transparent string-newtype identifier with the standard surface:
/// `Display`/`FromStr`, `TryFrom<String>`/`TryFrom<&str>` (parse-don't-validate,
/// `Error = CoreError`), transparent serde, `JsonSchema`, `as_str`,
/// `into_inner`, and (with the `mint` keyword) `new_v4`.
///
/// `Display` writes the bare inner string (no `kind:` prefix) so
/// `id.to_string().parse() == Ok(id)` is lossless and DB/JSON columns stay
/// byte-identical to the Rust strings. The non-empty invariant is enforced on
/// every fallible construction path (`FromStr`/`TryFrom`) via
/// [`CoreError::EmptyId`](crate::CoreError::EmptyId).
macro_rules! define_id {
    ($(#[$meta:meta])* $name:ident, mint) => {
        define_id!(@core $(#[$meta])* $name);
        impl $name {
            /// Mint a fresh dashed `UUIDv4`-backed identifier. The runtime's
            /// prefixed mints (`root-{request_id}`, `uuid4().hex[:16]`,
            /// `subagent_<counter>`) are produced by the owning crate, not by
            /// this generic helper.
            #[must_use]
            pub fn new_v4() -> Self {
                Self(::uuid::Uuid::new_v4().to_string().into())
            }
        }
    };
    ($(#[$meta:meta])* $name:ident, no_mint) => {
        define_id!(@core $(#[$meta])* $name);
    };
    (@core $(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[repr(transparent)]
        #[derive(
            Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord,
            ::serde::Serialize, ::schemars::JsonSchema,
        )]
        #[serde(transparent)]
        pub struct $name(::std::sync::Arc<str>);

        impl $name {
            /// Borrow the identifier as a string slice.
            #[must_use]
            pub fn as_str(&self) -> &str {
                &self.0
            }

            /// Consume the identifier, returning an owned `String` copy of the
            /// inner slice.
            #[must_use]
            pub fn into_inner(self) -> String {
                self.0.as_ref().to_owned()
            }
        }

        impl ::core::fmt::Display for $name {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl ::core::str::FromStr for $name {
            type Err = $crate::error::CoreError;
            fn from_str(s: &str) -> ::core::result::Result<Self, Self::Err> {
                if s.is_empty() {
                    return ::core::result::Result::Err(
                        $crate::error::CoreError::EmptyId { kind: stringify!($name) },
                    );
                }
                ::core::result::Result::Ok(Self(::std::sync::Arc::from(s)))
            }
        }

        impl<'de> ::serde::Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> ::core::result::Result<Self, D::Error>
            where
                D: ::serde::Deserializer<'de>,
            {
                let value = <::std::string::String as ::serde::Deserialize>::deserialize(
                    deserializer,
                )?;
                value.parse().map_err(::serde::de::Error::custom)
            }
        }

        impl ::core::convert::TryFrom<String> for $name {
            type Error = $crate::error::CoreError;
            fn try_from(s: String) -> ::core::result::Result<Self, Self::Error> {
                s.parse()
            }
        }

        impl ::core::convert::TryFrom<&str> for $name {
            type Error = $crate::error::CoreError;
            fn try_from(s: &str) -> ::core::result::Result<Self, Self::Error> {
                s.parse()
            }
        }
    };
}

define_id!(
    /// Identifier for a request row. Minted as `str(uuid.uuid4())` in
    /// `runtime/entry.py`; `new_v4` reproduces that dashed `UUIDv4` shape exactly.
    RequestId,
    mint
);
define_id!(
    /// Identifier for a persisted Task row. Opaque string; the root mint is
    /// `root-{request_id}` (derived by the owning request service from the
    /// injected request id, not `new_v4`).
    TaskId,
    mint
);
define_id!(
    /// Identifier for a delegated Workflow row.
    WorkflowId,
    mint
);
define_id!(
    /// Identifier for an Iteration row.
    IterationId,
    mint
);
define_id!(
    /// Identifier for an Attempt row.
    AttemptId,
    mint
);
define_id!(
    /// Identifier for an agent run (engine agent factory).
    AgentRunId,
    mint
);
define_id!(
    /// Identifier for a provisioned sandbox.
    SandboxId,
    mint
);
define_id!(
    /// Identifier for a single tool use. Model-assigned by the provider stream,
    /// so it has no local `new_v4` mint — minting one would be a bug.
    ToolUseId,
    no_mint
);
define_id!(
    /// Identifier for a sandbox tool-call invocation (tool dispatch).
    InvocationId,
    mint
);
define_id!(
    /// Identifier for a sandbox command-session tool handle.
    CommandSessionId,
    mint
);
#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)] // unwrap is permitted in tests (err-no-unwrap-prod)
    use super::*;
    use std::str::FromStr;

    // AC-types-01: Display/FromStr roundtrip for every id, over arbitrary
    // non-empty strings (proptest) plus the `UUIDv4` and `root-…` shapes; empty
    // input is rejected on every fallible path (CoreError::EmptyId).
    macro_rules! roundtrip_suite {
        ($modname:ident, $ty:ty) => {
            mod $modname {
                use super::*;

                proptest::proptest! {
                    #[test]
                    fn id_display_fromstr_roundtrip(s in "\\PC+") {
                        let id = <$ty>::from_str(&s).expect("non-empty parses");
                        proptest::prop_assert_eq!(id.to_string(), s);
                    }
                }

                #[test]
                fn explicit_shapes_roundtrip() {
                    for s in [
                        "3f2504e0-4f89-41d3-9a0c-0305e82c3301",
                        "root-abc123def4567890",
                    ] {
                        let id = <$ty>::from_str(s).expect("non-empty parses");
                        assert_eq!(id.to_string(), s);
                    }
                }

                #[test]
                fn empty_is_rejected_on_every_fallible_path() {
                    assert!(matches!(
                        <$ty>::from_str(""),
                        Err(crate::error::CoreError::EmptyId { .. })
                    ));
                    assert!(matches!(
                        <$ty>::try_from(""),
                        Err(crate::error::CoreError::EmptyId { .. })
                    ));
                    assert!(matches!(
                        <$ty>::try_from(String::new()),
                        Err(crate::error::CoreError::EmptyId { .. })
                    ));
                }
            }
        };
    }

    roundtrip_suite!(request_id, RequestId);
    roundtrip_suite!(task_id, TaskId);
    roundtrip_suite!(workflow_id, WorkflowId);
    roundtrip_suite!(iteration_id, IterationId);
    roundtrip_suite!(attempt_id, AttemptId);
    roundtrip_suite!(agent_run_id, AgentRunId);
    roundtrip_suite!(sandbox_id, SandboxId);
    roundtrip_suite!(tool_use_id, ToolUseId);
    roundtrip_suite!(invocation_id, InvocationId);
    roundtrip_suite!(command_session_id, CommandSessionId);

    // AC-types-02: transparent serde, no key duplication (GC-types-01).
    #[test]
    fn id_serde_transparent_single_key() {
        let id: TaskId = "t1".parse().unwrap();
        assert_eq!(serde_json::to_value(&id).unwrap(), serde_json::json!("t1"));
        let back: TaskId = serde_json::from_value(serde_json::json!("t1")).unwrap();
        assert_eq!(back, id);

        let empty = serde_json::from_value::<TaskId>(serde_json::json!(""));
        assert!(
            empty.is_err(),
            "transparent id serde must preserve the non-empty invariant"
        );

        #[derive(serde::Serialize)]
        struct Row {
            id: TaskId,
        }
        let row = serde_json::to_value(Row {
            id: "t1".parse().unwrap(),
        })
        .unwrap();
        assert_eq!(row, serde_json::json!({ "id": "t1" }));
        // The id appears under exactly one key (no `id` + `task_id` duplication).
        assert_eq!(row.as_object().unwrap().len(), 1);
    }

    #[test]
    fn try_from_and_parse_agree() {
        let a: TaskId = "x".parse().unwrap();
        let b = TaskId::try_from("x").unwrap();
        let c = TaskId::try_from(String::from("x")).unwrap();
        assert_eq!(a, b);
        assert_eq!(b, c);
        assert_eq!(a.as_str(), "x");
        assert_eq!(a.into_inner(), String::from("x"));
    }

    #[test]
    fn try_from_error_type_is_core_error() {
        // The named contract is `TryFrom<_, Error = CoreError>` — assert the
        // associated error type, not the std blanket `Infallible`.
        fn assert_core_error<T>()
        where
            T: TryFrom<&'static str, Error = crate::error::CoreError>,
        {
        }
        assert_core_error::<TaskId>();
    }

    #[test]
    fn new_v4_is_a_dashed_uuid() {
        let id = RequestId::new_v4();
        // 8-4-4-4-12 dashed form, parses back as a uuid.
        assert!(uuid::Uuid::parse_str(id.as_str()).is_ok());
        assert_eq!(id.as_str().len(), 36);
    }

    // AC-types-06 (ids portion): every id schemas as a JSON `string`.
    #[test]
    fn json_schema_ids_are_strings() {
        macro_rules! assert_string_schema {
            ($ty:ty) => {{
                let schema = serde_json::to_value(schemars::schema_for!($ty)).unwrap();
                assert_eq!(
                    schema["type"],
                    serde_json::json!("string"),
                    "{}",
                    stringify!($ty)
                );
            }};
        }
        assert_string_schema!(RequestId);
        assert_string_schema!(TaskId);
        assert_string_schema!(WorkflowId);
        assert_string_schema!(IterationId);
        assert_string_schema!(AttemptId);
        assert_string_schema!(AgentRunId);
        assert_string_schema!(SandboxId);
        assert_string_schema!(ToolUseId);
        assert_string_schema!(InvocationId);
        assert_string_schema!(CommandSessionId);
    }
}
