"""Stable timing metric keys emitted by sandbox subsystems."""

from __future__ import annotations

from enum import Enum


class TimingKey(str, Enum):
    APPLY_COMMIT = "occ.apply.commit_s"
    APPLY_COMMIT_QUEUE_WAIT = "occ.apply.commit_queue_wait_s"
    APPLY_COMMIT_RESUME_WAIT = "occ.apply.commit_resume_wait_s"
    APPLY_COMMIT_WORKER = "occ.apply.commit_worker_s"
    APPLY_MANIFEST_LAG = "occ.apply.manifest_lag"
    APPLY_TOTAL = "occ.apply.total_s"
    COMMIT_COLLECT_CHANGES = "occ.commit.collect_changes_s"
    COMMIT_DIRECT_APPLY_TOTAL = "occ.commit.direct_apply_changes_total_s"
    COMMIT_DIRECT_PATH_COUNT = "occ.commit.direct_path_count"
    COMMIT_DIRECT_READ_TOTAL = "occ.commit.direct_read_current_total_s"
    COMMIT_DIRECT_STAGE_TOTAL = "occ.commit.direct_stage_delta_total_s"
    COMMIT_GATED_APPLY_TOTAL = "occ.commit.gated_apply_changes_total_s"
    COMMIT_GATED_PATH_COUNT = "occ.commit.gated_path_count"
    COMMIT_GATED_READ_TOTAL = "occ.commit.gated_read_current_total_s"
    COMMIT_GATED_STAGE_TOTAL = "occ.commit.gated_stage_delta_total_s"
    COMMIT_PUBLISH_LAYER = "occ.commit.publish_layer_s"
    COMMIT_QUEUE_BATCH_SIZE = "occ.serial.batch_size"
    COMMIT_QUEUE_CAS_ATTEMPTS = "occ.serial.cas_attempts"
    COMMIT_QUEUE_CAS_EXHAUSTED = "occ.serial.cas_exhausted"
    COMMIT_QUEUE_COMMIT = "occ.serial.commit_s"
    COMMIT_QUEUE_RESULT_READY_AT = "_occ.serial.result_ready_at_s"
    COMMIT_QUEUE_WAIT = "occ.serial.queue_wait_s"
    COMMIT_SNAPSHOT = "occ.commit.snapshot_s"
    COMMIT_STAGER_WRITE_COUNT = "occ.commit.stager_write_count"
    COMMIT_STAGER_WRITE_TOTAL = "occ.commit.stager_write_total_s"
    COMMIT_TOTAL = "occ.commit.total_s"
    COMMIT_VALIDATE_GROUPS = "occ.commit.validate_groups_s"
    DIRECT_APPLY_CHANGES = "occ.direct.apply_changes_s"
    DIRECT_READ_CURRENT = "occ.direct.read_current_s"
    DIRECT_STAGE_DELTA = "occ.direct.stage_delta_s"
    GATED_APPLY_CHANGES = "occ.gated.apply_changes_s"
    GATED_READ_CURRENT = "occ.gated.read_current_s"
    GATED_STAGE_DELTA = "occ.gated.stage_delta_s"
    GITIGNORE_CACHE_HITS_TOTAL = "gitignore.cache_hits_total"
    GITIGNORE_CACHE_MISSES_TOTAL = "gitignore.cache_misses_total"
    LAYER_AUTO_SQUASH_DEPTH_AFTER = "layer_stack.auto_squash.depth_after"
    LAYER_AUTO_SQUASH_DEPTH_BEFORE = "layer_stack.auto_squash.depth_before"
    LAYER_AUTO_SQUASH_MANIFEST_VERSION = "layer_stack.auto_squash.manifest_version"
    LAYER_AUTO_SQUASH_MAX_DEPTH = "layer_stack.auto_squash.max_depth"
    LAYER_AUTO_SQUASH_RACED = "layer_stack.auto_squash.raced"
    LAYER_AUTO_SQUASH_RECHECK_TRIGGERED = "layer_stack.auto_squash.recheck_triggered"
    LAYER_AUTO_SQUASH_SKIPPED_IN_FLIGHT = "layer_stack.auto_squash.skipped_in_flight"
    LAYER_AUTO_SQUASH_TOTAL = "layer_stack.auto_squash.total_s"
    LAYER_TRANSACTION_LOCK_HELD = "layer_stack.transaction.lock_held_s"
    LAYER_TRANSACTION_LOCK_WAIT = "layer_stack.transaction.lock_wait_s"
    PREPARE_CURRENT_SNAPSHOT = "occ.prepare.current_snapshot_s"
    PREPARE_GITIGNORE = "occ.prepare.gitignore_s"
    PREPARE_GROUP_BY_ROUTE = "occ.prepare.group_by_route_s"
    PREPARE_GROUPS = "occ.prepare.prepare_groups_s"
    PREPARE_ROUTE_AND_BASE_HASH = "occ.prepare.route_and_base_hash_s"
    PREPARE_TOTAL = "occ.prepare.total_s"


__all__ = ["TimingKey"]
