[package]
name = "sandbox-runtime-layerstack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ignore.workspace = true
rayon.workspace = true
rustix.workspace = true
sandbox-runtime-layerstack-core.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
thiserror.workspace = true
zstd.workspace = true

[dev-dependencies]
base64.workspace = true
proptest.workspace = true

[lints]
workspace = true
