"""Public sandbox API package and compatibility request/result exports.

Request and result dataclasses are owned by :mod:`sandbox.models`; they are
re-exported here to preserve the existing public import path.
"""

from __future__ import annotations

from sandbox.models import (
    ConflictInfo,
    EditFileRequest,
    EditFileResult,
    GuardedResultBase,
    RawExecResult,
    ReadFileRequest,
    ReadFileResult,
    SandboxCaller,
    SandboxRequestBase,
    SandboxResultBase,
    SearchReplaceEdit,
    ShellRequest,
    ShellResult,
    WriteFileRequest,
    WriteFileResult,
)
from sandbox.api.default import (
    configure_default_client,
    context_preparer_for,
    create_sandbox,
    default_client,
    delete_sandbox,
    edit_file,
    ensure_sandbox_running,
    get_build_logs_url,
    get_health,
    get_sandbox,
    get_signed_preview_url,
    list_sandboxes,
    list_snapshots,
    raw_exec,
    read_file,
    set_default_client,
    set_sandbox_labels,
    shell,
    start_sandbox,
    stop_sandbox,
    write_file,
)
from sandbox.api.facade import SandboxClient

__all__ = [
    "ConflictInfo",
    "EditFileRequest",
    "EditFileResult",
    "GuardedResultBase",
    "RawExecResult",
    "ReadFileRequest",
    "ReadFileResult",
    "SandboxCaller",
    "SandboxRequestBase",
    "SandboxResultBase",
    "SearchReplaceEdit",
    "SandboxClient",
    "ShellRequest",
    "ShellResult",
    "WriteFileRequest",
    "WriteFileResult",
    "configure_default_client",
    "context_preparer_for",
    "create_sandbox",
    "default_client",
    "delete_sandbox",
    "edit_file",
    "ensure_sandbox_running",
    "get_build_logs_url",
    "get_health",
    "get_sandbox",
    "get_signed_preview_url",
    "list_sandboxes",
    "list_snapshots",
    "raw_exec",
    "read_file",
    "set_default_client",
    "set_sandbox_labels",
    "shell",
    "start_sandbox",
    "stop_sandbox",
    "write_file",
]
